In [3]:
import numpy as np  # Step1: NumPyをインポートする

# Step2: 行列AとBを多次元配列として定義
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

# Step3: 行列の積を計算
result = np.dot(A, B)

# Step4: 計算結果を表示
print("行列の積:")
print(result)

# Step5: 行列の要素の最大値を求める
max_value = np.max(result)
print("行列の要素の最大値:", max_value)

行列の積:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列の要素の最大値: 47
